In [22]:
import tensorflow as tf
import numpy as np

import cv2
import pyautogui

## Go to model card, here for details:
https://google.github.io/mediapipe/solutions/models.html

In [5]:
model_file = 'C:/Users/suman/Downloads/hand_landmark_full.tflite'
interpreter = tf.lite.Interpreter(model_path=model_file)

In [6]:
interpreter.allocate_tensors()

In [7]:
# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

In [6]:
# Test the model on random input data.
input_shape = input_details[0]['shape']
print(input_shape)
input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
interpreter.set_tensor(input_details[0]['index'], input_data)

[  1 224 224   3]


In [7]:
interpreter.invoke()

In [8]:
output_data = interpreter.get_tensor(output_details[0]['index'])
print(output_data)

[[1.10708542e+02 1.78701111e+02 9.36002107e-05 1.16525246e+02
  1.55639862e+02 7.67216015e+00 1.22199120e+02 1.30634430e+02
  9.94702339e+00 1.21300224e+02 1.11144073e+02 1.03095951e+01
  1.18885399e+02 9.52503662e+01 1.13462238e+01 1.16304886e+02
  1.05075401e+02 1.60085754e+01 1.14657585e+02 7.79017181e+01
  1.76496620e+01 1.16808105e+02 6.20959625e+01 1.74722805e+01
  1.19863037e+02 5.51077728e+01 1.78024101e+01 1.14302246e+02
  1.05211052e+02 1.21598454e+01 1.19409729e+02 7.36728287e+01
  1.32218924e+01 1.19018234e+02 5.80808220e+01 1.22761984e+01
  1.19659821e+02 4.86031036e+01 1.22752762e+01 1.11268036e+02
  1.07103569e+02 8.13047218e+00 1.20892929e+02 7.67701721e+01
  9.04858780e+00 1.21320282e+02 6.48137512e+01 1.01739302e+01
  1.25831596e+02 5.42307434e+01 1.16294289e+01 1.12972267e+02
  1.11313950e+02 4.61103153e+00 1.21751549e+02 8.67613220e+01
  8.32156849e+00 1.23665619e+02 7.47534027e+01 1.13709154e+01
  1.26023262e+02 6.57088776e+01 1.33023834e+01]]


https://www.tensorflow.org/lite/api_docs/python/tf/lite/Interpreter#get_output_details

In [23]:
print(output_details[0]['name'])
print(" ",output_details[0]['index'])
print(" ",output_details[0]['dtype'])
print(" ",output_details[0]['shape'])

print(output_details[1]['name'])
print(" ",output_details[1]['index'])
print(" ",output_details[1]['dtype'])
print(" ",output_details[1]['shape'])

print(output_details[2]['name'])
print(" ",output_details[2]['index'])
print(" ",output_details[2]['dtype'])
print(" ",output_details[2]['shape'])

print(output_details[3]['name'])
print(" ",output_details[3]['index'])
print(" ",output_details[3]['dtype'])
print(" ",output_details[3]['shape'])



Identity
  165
  <class 'numpy.float32'>
  [ 1 63]
Identity_1
  164
  <class 'numpy.float32'>
  [1 1]
Identity_2
  162
  <class 'numpy.float32'>
  [1 1]
Identity_3
  166
  <class 'numpy.float32'>
  [ 1 63]


In [33]:
output_data_0 = interpreter.get_tensor(output_details[0]['index'])
output_data_0

array([[1.10708542e+02, 1.78701111e+02, 9.36002107e-05, 1.16525246e+02,
        1.55639862e+02, 7.67216015e+00, 1.22199120e+02, 1.30634430e+02,
        9.94702339e+00, 1.21300224e+02, 1.11144073e+02, 1.03095951e+01,
        1.18885399e+02, 9.52503662e+01, 1.13462238e+01, 1.16304886e+02,
        1.05075401e+02, 1.60085754e+01, 1.14657585e+02, 7.79017181e+01,
        1.76496620e+01, 1.16808105e+02, 6.20959625e+01, 1.74722805e+01,
        1.19863037e+02, 5.51077728e+01, 1.78024101e+01, 1.14302246e+02,
        1.05211052e+02, 1.21598454e+01, 1.19409729e+02, 7.36728287e+01,
        1.32218924e+01, 1.19018234e+02, 5.80808220e+01, 1.22761984e+01,
        1.19659821e+02, 4.86031036e+01, 1.22752762e+01, 1.11268036e+02,
        1.07103569e+02, 8.13047218e+00, 1.20892929e+02, 7.67701721e+01,
        9.04858780e+00, 1.21320282e+02, 6.48137512e+01, 1.01739302e+01,
        1.25831596e+02, 5.42307434e+01, 1.16294289e+01, 1.12972267e+02,
        1.11313950e+02, 4.61103153e+00, 1.21751549e+02, 8.676132

In [34]:
output_data_1 = interpreter.get_tensor(output_details[1]['index'])
output_data_1

array([[0.00860468]], dtype=float32)

In [35]:
output_data_2 = interpreter.get_tensor(output_details[2]['index'])
output_data_2

array([[0.46441147]], dtype=float32)

In [37]:
output_data_3 = interpreter.get_tensor(output_details[3]['index'])
output_data_3

array([[ 6.02237508e-03,  7.67518282e-02,  3.87248024e-02,
         1.25506073e-02,  5.78480661e-02,  4.18520570e-02,
         1.77433491e-02,  3.29556763e-02,  3.49037945e-02,
         1.16502158e-02,  7.98656046e-03,  2.14334242e-02,
         9.38664377e-03, -1.61155462e-02,  9.96954739e-03,
         5.36477566e-03, -4.24903631e-03,  9.01447237e-03,
         1.66255236e-03, -2.65102386e-02, -2.27767229e-03,
         3.33292037e-03, -4.16475385e-02,  3.23686004e-03,
         1.79009140e-03, -5.67043871e-02,  3.42591107e-03,
        -4.84221429e-03, -2.76446342e-03,  2.31543928e-03,
        -2.18552351e-03, -4.30181026e-02, -6.63595647e-03,
        -3.81018221e-03, -6.07405901e-02, -4.40052152e-03,
        -8.72820616e-03, -7.98309445e-02, -2.89678574e-05,
        -5.26937097e-03, -2.56948173e-04, -7.49412924e-03,
        -2.66161561e-03, -3.40172052e-02, -1.30470395e-02,
         3.02687287e-03, -5.22272140e-02, -4.03909385e-03,
         4.28539515e-03, -6.41643554e-02,  1.09213442e-0

In [45]:
cap = cv2.VideoCapture(0)
# You can setup your camera settings
cap.set(3,1920)
cap.set(4,1080)

cv2.namedWindow('image')
# cv2.createTrackbar('a','image',0,255,nothing)
while cap.isOpened():
    re, frame = cap.read()
    # convert the image to RGB
    image = cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
    
        # flip the image
    image = cv2.flip(image,1)
    
    image.flags.writeable = False
    output_data_0, output_data_1, output_data_2, output_data_3 = process_frame(image)
    
    image.flags.writeable = True
    cv2.putText(image, f'output_data_1 {output_data_1}', (20,50), cv2.FONT_HERSHEY_SIMPLEX, 1, (300, 50, 50), 2)
    cv2.putText(image, f'output_data_2 {output_data_2}', (20,80), cv2.FONT_HERSHEY_SIMPLEX, 1, (300, 50, 50), 2)
    
    cv2.imshow('image',image)

#     print(output_data_1," ", output_data_1)
    if cv2.waitKey(10) & 0xff == ord('q'):
        break
cv2.destroyAllWindows()

In [29]:
cv2.destroyAllWindows()

In [43]:
# resizer = tf.image.resize(
#     images, size, method=ResizeMethod.BILINEAR, preserve_aspect_ratio=False,
#     antialias=False, name=None
# )

def process_frame(frame):
#     print("frame shape: ", frame.shape)
    resized_frame = tf.image.resize(frame, [224, 224], preserve_aspect_ratio=False)
#     print("rsized1 shape: ", resized_frame.shape)
    resized_frame = np.expand_dims(resized_frame, axis=0)
#     print("rsized shape: ", resized_frame.shape)
    interpreter.set_tensor(input_details[0]['index'], resized_frame)
    interpreter.invoke()
    output_data_0 = interpreter.get_tensor(output_details[0]['index'])
    output_data_1 = interpreter.get_tensor(output_details[1]['index'])
    output_data_2 = interpreter.get_tensor(output_details[2]['index'])
    output_data_3 = interpreter.get_tensor(output_details[3]['index'])
    return output_data_0, output_data_1, output_data_2, output_data_3

In [ ]:
# Test the model on random input data.
input_shape = input_details[0]['shape']
print(input_shape)
input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
interpreter.set_tensor(input_details[0]['index'], input_data)

In [41]:
input_details[0]

{'name': 'input_1',
 'index': 0,
 'shape': array([  1, 224, 224,   3]),
 'shape_signature': array([  1, 224, 224,   3]),
 'dtype': numpy.float32,
 'quantization': (0.0, 0),
 'quantization_parameters': {'scales': array([], dtype=float32),
  'zero_points': array([], dtype=int32),
  'quantized_dimension': 0},
 'sparsity_parameters': {}}

In [42]:
input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
input_data

array([[[[0.25430682, 0.40746945, 0.16861366],
         [0.29629025, 0.4192725 , 0.01039161],
         [0.9035795 , 0.14442316, 0.31675768],
         ...,
         [0.6228682 , 0.5205476 , 0.8174807 ],
         [0.69619864, 0.95410913, 0.6030253 ],
         [0.33573774, 0.42758608, 0.6578484 ]],

        [[0.16462192, 0.3482242 , 0.9607842 ],
         [0.6842862 , 0.9031328 , 0.18337312],
         [0.85681653, 0.83401006, 0.8285552 ],
         ...,
         [0.93545836, 0.53672487, 0.28406367],
         [0.21627063, 0.43438244, 0.6623999 ],
         [0.6688025 , 0.74100274, 0.67211455]],

        [[0.9767639 , 0.3705547 , 0.03942221],
         [0.43846482, 0.6986182 , 0.67793685],
         [0.05185306, 0.47779995, 0.9008208 ],
         ...,
         [0.90953976, 0.75774944, 0.3276761 ],
         [0.54370075, 0.07237178, 0.26100832],
         [0.32656583, 0.67829823, 0.36056882]],

        ...,

        [[0.01348164, 0.23558775, 0.72278917],
         [0.34436166, 0.87609345, 0.02033561]

In [45]:
resizer = tf.keras.layers.Resizing(224, 224)

AttributeError: module 'tensorflow.keras.layers' has no attribute 'Resizing'

In [43]:
input_shape

array([  1, 224, 224,   3])

In [52]:
tf.__version__

'2.5.0'